[package]
name = "lazytestr"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-parser = "0.9.1"
colored = "2.1.0"
crossterm = "0.27.0"
env_logger = "0.11.3"
ignore = "0.4.22"
log = "0.4.22"
notify = "6.1.1"
regex = "1.10.5"
simplelog = "0.12.2"
tui = "0.19.0"
